In [1]:
# Imports
import time

# Dependencies
import pandas as pd

# Library
from api_builder.fsm import menus
from api_builder.fsm.states import State
from api_builder.fsm.constants import NATIONS
from api_builder.fsm import fsm
from utils.utils import construct_rules
from api_builder.fsm.url_parser import parse_links
from api_builder.fsm.fetch import fetch_routine
from pipeline.builder import VanguardPipeline
from api_builder.fsm.query_builder import make_query
from data.vanguard_data import VanguardStorage
from api_builder.fsm.scrap import main_scrap_routine
from parsers.vanguard_parser import VanguardParser
from classifier.vanguard_classifier import VanguardClassifier
from api_builder.vanguard_api_build import MediaWikiAPI, VanguardScrapper
from api_builder.api_request import header
from cards.fsm						import CardFSM

In [2]:
# Url Parser
web = MediaWikiAPI()
pipeline = VanguardPipeline(
	VanguardParser(),
	VanguardStorage(),
	VanguardScrapper(web),
	VanguardClassifier()
)
await pipeline.scrapper.api.init_session()
state_machine = fsm.FSMContext()
state = State.ENTRY_POINT
while (state != State.END):
	if (state == State.ENTRY_POINT):
		state = menus.entry_point(state_machine)
	elif (state == State.SELECT_MAIN_CATEGORY):
		state = menus.select_category(state_machine)
	elif (state == State.SELECT_SUBCATEGORY):
		state = menus.select_subcategory(state_machine)
	elif (state == State.BUILD_QUERY):
		state = make_query(state_machine)
	elif (state == State.FETCH):
		state = await fetch_routine(state_machine, pipeline)
	elif (state == State.PARSE):
		pipeline.classifier._define_rules(construct_rules(state_machine.main_category.capitalize()))
		state = parse_links(state_machine, pipeline)
		state = State.END
time.sleep(4)

Welcome to VanguardTCGScrapper


What info do you need from the website?
0 : boosters
1 : specials
2 : decks
3 : others
4 : cards
You selected: boosters
Which subcategory you want to scrap?
indentify it with the index number:

0:  Booster Sets
1:  Extra Booster Sets
2:  Character Booster Sets
3:  Clan Booster Sets
4:  Title Booster Sets
5:  Unique Booster Sets

In [ ]:
ls = [[1], [2]]
len(ls)

In [ ]:
state_machine.data

In [ ]:
from data.check_data_base import build_set_path

for block in ["LB", "LL", "G", "V", "D", "DZ"]:
	consult = pipeline.parser.make_consults(getattr(pipeline.storage, block.lower()))
	print(consult)
	for tpl in consult.values():
		print(f"voy a pasar esta consulta: {tpl}")
		time.sleep(6)
		api_result = await pipeline.scrapper.api.get(
			params=tpl,
			headers=header
		)
		print(api_result)
		wikitex = pipeline.scrapper.obtain_wikitex(api_result)
		data = pipeline.scrapper.make_cardlist_from_str(wikitex=wikitex)
		infobox = pipeline.parser.infobox(wikitex)
		is_d = False
		is_deck = False
		if (block in ["D", "DZ"]):
			is_d = True
		rows = pipeline.storage.prepare_data(data, 6, is_d=is_d, is_deck=is_deck, infobox=infobox)
		df = pd.DataFrame(rows, columns=[
			"CardNo", "Name", "Grade", "Faction",
			"FactionType", "Type", "Rarity", "Release"
		])
		set_number = pipeline.classifier.obtain_set_number(
			data[0]
		)
		path = build_set_path(
			category="boosters",
			set_type="main",
			block=block,
			set_number=set_number
		)
		path.parent.mkdir(
			parents=True,
			exist_ok=True
		)
		df.to_parquet(path)

		print(data)

In [17]:
db = pd.read_parquet("database/boosters/booster sets/v/set_08.parquet")
db.loc[db["Code"] == "None"]

Empty DataFrame
Columns: [Code, Name, Grade, Faction, FactionType, Type, Rarity, Release, URL]
Index: []

In [18]:
db

,Code,Name,Grade,Faction,FactionType,Type,Rarity,Release,URL
0,V-BT08/001,Alter Ego Messiah,3,[Link Joker],Clan,Force,VR+SP,"June 19, 2020 (JP)September 4, 2020 (EN)",Alter Ego Messiah (V Series)
1,V-BT08/002,"Dragonic Overlord ""The X""",3,[Kagero],Clan,Force,VR+SP,"June 19, 2020 (JP)September 4, 2020 (EN)","Dragonic Overlord ""The X"" (V Series)"
2,V-BT08/003,"Dragonic Blademaster ""Souen""",3,[Kagero],Clan,Force,VR+SP,"June 19, 2020 (JP)September 4, 2020 (EN)","Dragonic Blademaster ""Souen"""
3,V-BT08/004,"Supreme Heavenly Battle Deity, Susanoo",3,[Oracle Think Tank],Clan,Protect,VR+SP,"June 19, 2020 (JP)September 4, 2020 (EN)","Supreme Heavenly Battle Deity, Susanoo (V Series)"
4,V-BT08/005,"Great Cosmic Hero, Grandgallop",3,[Dimension Police],Clan,Force,VR+SP,"June 19, 2020 (JP)September 4, 2020 (EN)","Great Cosmic Hero, Grandgallop (V Series)"
...,...,...,...,...,...,...,...,...,...
97,V-BT08/SP28,"Weather Forecaster, Miss Mist",0,[Oracle Think Tank],Clan,DrawPG,SP,"June 19, 2020 (JP)September 4, 2020 (EN)","Weather Forecaster, Miss Mist (V Series)"
98,V-BT08/SP30,Quick Shield,0,[],Clan,Blitz Order,SP,"June 19, 2020 (JP)September 4, 2020 (EN)",Quick Shield
99,V-BT08/SP31,Diamond Ace,0,[Dimension Police],Clan,DrawPG,SP,"June 19, 2020 (JP)September 4, 2020 (EN)",Diamond Ace (V Series)
100,V-BT08/SP33,Quick Shield,0,[],Clan,Blitz Order,SP,"June 19, 2020 (JP)September 4, 2020 (EN)",Quick Shield
101,V-BT08/T01,Vision Token,3,[],Clan,Token unit,,"June 19, 2020 (JP)September 4, 2020 (EN)",Vision Token

In [ ]:
db[90:100]

In [ ]:
db[119:210]

In [3]:
pipeline.storage.v

['V Booster Set 01: Unite! Team Q4',
 'V Booster Set 02: Strongest! Team AL4',
 'V Booster Set 03: Miyaji Academy Cardfight Club',
 'V Booster Set 04: Vilest! Deletor',
 'V Booster Set 05: Aerial Steed Liberation',
 'V Booster Set 06: Phantasmal Steed Restoration',
 'V Booster Set 07: Infinideity Cradle',
 'V Booster Set 08: Silverdust Blaze',
 "V Booster Set 09: Butterfly d'Moonlight",
 'V Booster Set 10: Phantom Dragon Aeon',
 'V Booster Set 11: Storm of the Blue Cavalry',
 'V Booster Set 12: Divine Lightning Radiance']

In [4]:
dz_consults = pipeline.parser.make_consults(pipeline.storage.v, "consult")

In [6]:
dz_consults[8]

{'action': 'query',
 'format': 'json',
 'prop': 'revisions',
 'titles': "V Booster Set 09: Butterfly d'Moonlight",
 'rvprop': 'content',
 'rvslots': 'main'}

In [ ]:
dz_consults[0]

In [7]:
api_answer = await pipeline.scrapper.api.get(dz_consults[8], headers=header)

In [ ]:
api_answer["parse"]["text"]["*"]

In [8]:
api_answer

{'batchcomplete': '',
 'query': {'pages': {'1977459': {'pageid': 1977459,
    'ns': 0,
    'title': "V Booster Set 09: Butterfly d'Moonlight",
    'revisions': [{'slots': {'main': {'contentmodel': 'wikitext',
        'contentformat': 'text/x-wiki',
        '*': '{{Infobox\n|Box title = VGE-V-BT09:Butterfly d\'Moonlight\n|image = File:VGE-V-BT09.png\n|Row 1 title = Japanese Name\n|Row 1 info = {{Ruby|蝶魔月影|ちょうまげつえい}}\n|Row 2 title = Phonetic\n|Row 2 info = Chōma Getsuei\n|Row 3 title = Translation\n|Row 3 info = Butterfly & Magic Under Moon\'s Shadow\n|Row 4 title = Release Date\n|Row 4 info = July 31, 2020 (JP)<br>October 2, 2020 (EN)\n|Row 5 title = Set Gallery Japanese\n|Row 5 info = [[Set Gallery:VG-V-BT09|VG-V-BT09]]\n|Row 6 title = Set Gallery English\n|Row 6 info = [[Set Gallery:VGE-V-BT09|VGE-V-BT09]]\n|Row 7 title = Previous Set\n|Row 7 info = [[V Booster Set 08: Silverdust Blaze|Silverdust Blaze]]\n|Row 8 title = Next Set\n|Row 8 info = [[V Booster Set 10: Phantom Dragon Aeon|Phantom Dragon Aeon]]\n}}\'\'\'Butterfly d\'Moonlight\'\'\' is the 9th {{V}} {{PR|BT}} released in the Japanese and English formats.\n\n==Contents==\n*Includes 94 cards (5 VR, 11 RRR, 12 RR, 22 R, 44 C) + 1 [[marker]] card + 36 Parallel cards (34 SP, 2 RLR).\n**SP Clan Packs are included.\n*There are 88 new cards and 6 reprints.\n*Includes support for the {{VLink|Murakumo}}, {{VLink|Dark Irregulars}}, {{VLink|Pale Moon}} and {{VLink|Granblue}} [[clan]]s.\n*Introduces the "[[Treasures]]" [[marker]].\n*Each English edition display includes a bonus clan die.\n*The package illustration features {{VLink|Vampire Princess of Night Fog, Nightrose}} and {{VLink|Masked Magician, Harri}}.\n*The booster\'s slogan is "\'\'Back to the dream stage——\'\'".\n\n==Video==\n<gallery captionalign="center" position="center" widths="300">\n「カードファイト!! ヴァンガード」ブースターパック第9弾「蝶魔月影」|Japanese commercial\nCardfight!! Vanguard Booster Pack Vol. 09- Butterfly d’Moonlight|English commercial \n</gallery>\n\n==Card List==\n{{CardList/header/V}}\n{{CardListV|V-BT09/001|\u200eMasked Magician, Harri|V|3|Pale Moon|Accel|VR+SP+RLR}}\n{{CardListV|V-BT09/002|Vampire Princess of Night Fog, Nightrose|V|3|Granblue|Protect|VR+SP+RLR}}\n{{CardListV|V-BT09/003|Stealth Rogue of Revelation, Yasuie|V|3|Murakumo|Accel|VR+SP}}\n{{CardListV|V-BT09/004|Scharhrot Vampir|V|3|Dark Irregulars|Protect|VR+SP}}\n{{CardListV|V-BT09/005|Silver Thorn Dragon Empress, Venus Luquier|V|3|Pale Moon|Accel|VR+SP}}\n{{CardListV|V-BT09/006|Ambush Demon Stealth Rogue, Yasuie Tenma|V|3|Murakumo|Accel|RRR+SP}}\n{{CardListV|V-BT09/007|Demon Claw Stealth Rogue, Yoitogi||2|Murakumo||RRR+SP}}\n{{CardListV|V-BT09/008|Gateway Stealth Rogue, Ataka|V|1|Murakumo||RRR+SP}}\n{{CardListV|V-BT09/009|Abominable One, Gilles de Rais|V|3|Dark Irregulars|Protect|RRR+SP}}\n{{CardListV|V-BT09/010|Succubus of Pure Love|V|1|Dark Irregulars||RRR+SP}}\n{{CardListV|V-BT09/011|Card Dealer, Jacqueline|V|2|Pale Moon||RRR+SP}}\n{{CardListV|V-BT09/012|Silver Thorn Diva, Selvia||2|Pale Moon||RRR+SP}}\n{{CardListV|V-BT09/013|Masquerade Bunny|V|1|Pale Moon||RRR+SP}}\n{{CardListV|V-BT09/014|Lord of the Seven Seas, Nightmist|V|3|Granblue|Protect|RRR+SP}}\n{{CardListV|V-BT09/015|Pirate Swordsman, Colombard|V|2|Granblue||RRR+SP}}\n{{CardListV|V-BT09/016|Tommy the Ghostie Brothers|V|1|Granblue||RRR+SP}}\n{{CardListV|V-BT09/017|Dueling Dragon, ZANTETHU||3|Murakumo|Accel|RR}}\n{{CardListV|V-BT09/018|Wisteria Flower Stealth Rogue, Takehime||1|Murakumo||RR}}\n{{CardListV|V-BT09/019|Stealth Rogue of the Fiendish Blade, Masamura|V|0|Murakumo|CritShield|RR}}\n{{CardListV|V-BT09/020|Demonted Executioner|V|2|Dark Irregulars||RR}}\n{{CardListV|V-BT09/021|Edge in the Darkness|V|1|Dark Irregulars||RR}}\n{{CardListV|V-BT09/022|One-eyed Succubus|V|0|Dark Irregulars|CritShield|RR}}\n{{CardListV|V-BT09/023|Lore Pigeon, Pop||2|Pale Moon||RR}}\n{{CardListV|V-BT09/024|Moonlight Melody Tamer, Betty|V|1|Pale Moon||RR+SP}}\n{{CardListV|V-BT09/025|Darkside Sword Master|V|0|Pale Moon|CritShield|RR}}\n{{CardListV|V-BT09/026|Thin-mist Banshee||2|Granblue||RR+SP}}\n{{CardListV|V-BT09/027|Seven Seas Pillager, Nightspinel|V|2|Granblue||RR}}\n{{CardListV|V-BT09/028|Rampage Shade|V|0|Granblue|CritShield|RR}}\n{{CardListV|V-BT09/029|Stealth Rogue of Rough Skills, Masunari||3|Murakumo||R}}\n{{CardListV|V-BT09/030|Stealth Dragon, Plumblame||2|Murakumo||R}}\n{{CardListV|V-BT09/031|Stealth Rogue of Noh Masks, Awazu||2|Murakumo||R}}\n{{CardListV|V-BT09/032|Flute-blowing Stealth Rogue, Kadoggu||1|Murakumo||R}}\n{{CardListV|V-BT09/033|Backward Arrester||1|Murakumo||R}}\n{{CardListV|V-BT09/034|Austere Heater||3|Dark Irregulars|Protect|R}}\n{{CardListV|V-BT09/035|Flap Fixer||3|Dark Irregulars|Protect|R}}\n{{CardListV|V-BT09/036|Doppel Vampir|V|2|Dark Irregulars||R}}\n{{CardListV|V-BT09/037|Stone Framer||1|Dark Irregulars||R}}\n{{CardListV|V-BT09/038|Deflect Sweet||1|Dark Irregulars||R}}\n{{CardListV|V-BT09/039|Starry Pop Dragon||4|Pale Moon||R}}\n{{CardListV|V-BT09/040|Blending Burner||3|Pale Moon|Accel|R}}\n{{CardListV|V-BT09/041|Magia Doll, Prana||2|Pale Moon||R}}\n{{CardListV|V-BT09/042|Magia Doll, Lunatec Dragon||2|Pale Moon||R}}\n{{CardListV|V-BT09/043|Silver Thorn Handlegrip, Linnea||1|Pale Moon||R}}\n{{CardListV|V-BT09/044|Nightmare Doll, Marion||1|Pale Moon||R}}\n{{CardListV|V-BT09/045|Skeleton Pirate Skipper||3|Granblue|Protect|R}}\n{{CardListV|V-BT09/046|Witch Doctor of Languor, Negrolazy|V|2|Granblue||R}}\n{{CardListV|V-BT09/047|Seven Seas Master Swordsman, Slash Shade|V|2|Granblue||R}}\n{{CardListV|V-BT09/048|Seven Seas Helmsman, Nightcrow|V|1|Granblue||R}}\n{{CardListV|V-BT09/049|Witch Doctor of Powdered Bone, Negrobone|V|1|Granblue||R}}\n{{CardListV|V-BT09/050|Soul-barette Roulette||3||Normal Order|R}}\n{{CardListV|V-BT09/051|Covert Demonic Dragon, Vehemel Fudou||3|Murakumo||C}}\n{{CardListV|V-BT09/052|Stealth Dragon, Shuratoguro||2|Murakumo||C}}\n{{CardListV|V-BT09/053|Impalpable Stealth Rogue, Kuninaga||2|Murakumo||C}}\n{{CardListV|V-BT09/054|Stealth Rogue of Temari Song, Miyagiku||1|Murakumo||C}}\n{{CardListV|V-BT09/055|Inexhaustible Stealth Rogue, Tokitsune||1|Murakumo||C}}\n{{CardListV|V-BT09/056|Stealth Dragon, Adverspike||0|Murakumo||C}}\n{{CardListV|V-BT09/057|Stealth Beast, Moon Edge|V|0|Murakumo|Critical|C}}\n{{CardListV|V-BT09/058|Stealth Fiend, Ever Wing||0|Murakumo|Draw|C}}\n{{CardListV|V-BT09/059|Stealth Beast, Ahead Panther||0|Murakumo|Front|C}}\n{{CardListV|V-BT09/060|Stealth Fiend, Bamboo Fox||0|Murakumo|Heal|C}}\n{{CardListV|V-BT09/061|Inflict Stamper||3|Dark Irregulars|Protect|C}}\n{{CardListV|V-BT09/062|Gravitate Core Master||3|Dark Irregulars|Protect|C}}\n{{CardListV|V-BT09/063|Exact Frozen||2|Dark Irregulars||C}}\n{{CardListV|V-BT09/064|Prognos Drei||2|Dark Irregulars||C}}\n{{CardListV|V-BT09/065|Blemish Spire||2|Dark Irregulars||C}}\n{{CardListV|V-BT09/066|Tornado Genitor||1|Dark Irregulars||C}}\n{{CardListV|V-BT09/067|Werfleder Ordonnaz|V|0|Dark Irregulars||C+SP}}\n{{CardListV|V-BT09/068|Dark Knight of Nightmareland|V|0|Dark Irregulars|Critical|C}}\n{{CardListV|V-BT09/069|Pulse Taker||0|Dark Irregulars|Draw|C}}\n{{CardListV|V-BT09/070|Alice of Nightmareland|V|0|Dark Irregulars|Heal|C}}\n{{CardListV|V-BT09/071|Fesbright Escaper||2|Pale Moon||C}}\n{{CardListV|V-BT09/072|Flame Rowdy||2|Pale Moon||C}}\n{{CardListV|V-BT09/073|Genteel Opener||2|Pale Moon||C}}\n{{CardListV|V-BT09/074|Tempting Hoopster||1|Pale Moon||C}}\n{{CardListV|V-BT09/075|Magia Doll, Darkside Mirror Master||1|Pale Moon||C}}\n{{CardListV|V-BT09/076|Magia Doll, Flying Peryton||1|Pale Moon||C}}\n{{CardListV|V-BT09/077|Wonder Hanger||1|Pale Moon||C}}\n{{CardListV|V-BT09/078|Happiness Collector|V|0|Pale Moon||C+SP}}\n{{CardListV|V-BT09/079|\u200eSilver Thorn, Barking Dragon|V|0|Pale Moon|Critical|C}}\n{{CardListV|V-BT09/080|Mirror Lord Surmounter||0|Pale Moon|Draw|C}}\n{{CardListV|V-BT09/081|Silver Thorn Beast Tamer, Serge|V|0|Pale Moon|Front|C}}\n{{CardListV|V-BT09/082|Tender Breeder|V|0|Pale Moon|Heal|C}}\n{{CardListV|V-BT09/083|Parliament Shade||3|Granblue||C}}\n{{CardListV|V-BT09/084|Forebode Ghost Ship||3|Granblue|Protect|C}}\n{{CardListV|V-BT09/085|Wracking Frankhini||2|Granblue||C}}\n{{CardListV|V-BT09/086|Night-playing Zombie||1|Granblue||C}}\n{{CardListV|V-BT09/087|Cyrille the Ghostie||1|Granblue||C}}\n{{CardListV|V-BT09/088|Witch Doctor of the Seven Seas, Raistutor|V|1|Granblue||C}}\n{{CardListV|V-BT09/089|Skeleton Sea Navigator||1|Granblue||C}}\n{{CardListV|V-BT09/090|Undying Departed, Grenache|V|0|Granblue||C+SP}}\n{{CardListV|V-BT09/091|Seven Seas Apprentice, Nightrunner|V|0|Granblue||C}}\n{{CardListV|V-BT09/092|Mortal Mimic||0|Granblue|Critical|C}}\n{{CardListV|V-BT09/093|Gunner Francette||0|Granblue|Draw|C}}\n{{CardListV|V-BT09/094|Good Luck Charm Banshee|V|0|Granblue|Heal|C}}\n{{CardListV|V-BT09/T01|Treasures|||||}}\n{{CardListV|V-BT09/SP19|Hades Hypnotist|V|0|Pale Moon|DrawPG|SP}}\n{{CardListV|V-BT09/SP21|Quick Shield||0|||SP}}\n{{CardListV|V-BT09/SP22|Gust Djinn|V|0|Granblue|DrawPG|SP}}\n{{CardListV|V-BT09/SP24|Quick Shield||0|||SP}}\n{{CardListV|V-BT09/SP25|Stealth Beast, Leaves Mirage|V|0|Murakumo|DrawPG|SP}}\n{{CardListV|V-BT09/SP26|Masago Stealth Rogue, Goemon|V|0|Murakumo||SP}}\n{{CardListV|V-BT09/SP27|Quick Shield||0|||SP}}\n{{CardListV|V-BT09/SP28|Number of Terror|V|3|Dark Irregulars|Protect|SP}}\n{{CardListV|V-BT09/SP29|March Rabbit of Nightmareland|V|0|Dark Irregulars|DrawPG|SP}}\n{{CardListV|V-BT09/SP31|Quick Shield||0|||SP}}\n{{CardListV|V-BT09/SP32|Silver Thorn, Rising Dragon|V|2|Pale Moon||SP}}\n{{CardListV|V-BT09/SP33|Silver Thorn Conjurer, Romy||1|Pale Moon||SP}}\n{{CardListV|V-BT09/SP34|Silver Thorn Assistant, Ionela|V|0|Pale Moon||SP}}\n{{CardList/footer}}\n<br />\n\n==Clan/Grade Breakdown==\n{{ClanGradeBD/header}}\n{{ClanGradeBDV|Murakumo|6(+2)|6|5|5|0|22(+2)}}\n{{ClanGradeBDV|Dark Irregulars|5(+1)|5|5|6(+1)|0|21(+2)}}\n{{ClanGradeBDV|Pale Moon|6(+2)|8(+1)|8(+1)|3|1|26(+4)}}\n{{ClanGradeBDV|Granblue|6(+1)|7|6|5|0|24(+1)}}\n{{ClanGradeBDV||0|0|0|1|0|1}}\n{{ClanGradeBD/footer}}\n<br />\n\n{{Booster Sets}}'}}}]}}}}

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup = BeautifulSoup(api_answer["parse"]["text"]["*"], "html.parser")

In [9]:
wikitex = pipeline.scrapper.obtain_wikitex(api_answer)
data = pipeline.scrapper.make_cardlist_from_str(wikitex=wikitex)
infobox = pipeline.parser.infobox(wikitex)

In [13]:
card_fsm = CardFSM(state_machine)

In [14]:
data[95]

'{{CardListV|V-BT09/SP19|Hades Hypnotist|V|0|Pale Moon|DrawPG|SP}}'

In [ ]:
import unicodedata
def clean_text(text: str) -> str:
	text = unicodedata.normalize("NFKC", text)

	invisible_chars = [
		"\u200e",
		"\u200f",
		"\u200b",
		"\ufeff"
	]

	for char in invisible_chars:
		text = text.replace(char, "")

	return (text.strip())

In [ ]:
clean_text(str(data[15].params[1].value).strip())

In [ ]:
data[0].params[1]

In [ ]:
wiki = pipeline.scrapper.obtain_links(api_answer)

In [ ]:
pipeline.parser.clean_trash_from_set(state_machine.data["page"], wiki, 4, reverse=True)

In [ ]:
data[0].params[1].value

In [ ]:
pipeline.storage.lb

In [ ]:
type(wiki[0])

In [ ]:
param = {
    "action": "parse",
    "page": "V Booster Set 01: Unite! Team Q4",
    "prop": "links",
    "format": "json"
}

In [ ]:
api_answer = await pipeline.scrapper.api.get(params=param, headers=header)

In [ ]:
api_answer

In [ ]:
print(pipeline.storage.prepare_data([data[0]], card_fsm))

In [ ]:
df = pd.DataFrame(data, columns=[
	"CardNo", "Name", "Grade", "Faction",
	"FactionType", "Type", "Rarity", "Release"
])

In [ ]:
df

In [ ]:
await main_scrap_routine(pipeline.parser, pipeline.storage, pipeline.scrapper, pipeline.classifier)

In [ ]:
api_answer["query"]["pages"]["525299"]["revisions"][0]["slots"]["main"]["*"]

In [ ]:
api_result = await pipeline.scrapper.api.get(
	params=dz_consults[0],
	headers=header
)

In [ ]:
api_result

In [ ]:
df = pd.read_parquet("data/database/boosters/booster sets/v/set_-1_8.parquet")

In [ ]:
df